### ISSUE TITLE
[Modify] 반응형 분기 변경

### ISSUE THREAD

**Issue by hyejineee** [korea-snorkeling-point/snorkeling-point-client#67]
## ✨ Issue

* Group : style
* Detail : 현재 반응형 분기 5개 -> 3개로 변경 

## ✨ Todo
* 사이즈 조정 
* 기존 코드 수정

**Comment by hyejineee** [comment]
![난못해](https://user-images.githubusercontent.com/44992033/218730020-485bb477-151d-4357-b2c8-e1c04daa99b1.jpeg)

**Comment by kyeongwxx** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ프사는 왜이래 또..

저 시험 좀 치고 같이 나눠봅시다요

**Comment by hyejineee** [comment]
녜,,,, 최대한 수정이 적은 쪽으로 머리 쥐어짜보겠슴다
